### PR TITLE
Fix UUID issue

### PR DESCRIPTION
**Pull request by SampsonCrowley**
Fixed an issue where a default value regex test `/-?\d+/` was matching against `uuid_generate_v1()` and `uuid_generate_v4()`

added test to confirm null default on UUID default columns

probably could still use a validation to confirm UUID but i don't think thats vital right now

### CODE REVIEW

**Comment by PhilWaldmann** [comment]
Hey! Thanks!!

Oh, the `1` comes from the `..._v1`.

Could you please add the newly added `uuid` type to the `simplifiedType` method of `attributes.js`. Otherwiese Openrecord will use the string type for uuid.

so that this 
```js
it('attribute id is type uuid', function(next){
    store.ready(function(){
      var UuidTest = store.Model('UuidTest')
      UuidTest.definition.attributes.id.type.name.should.be.equal('uuid')
      next()
    })
  })
```
wil pass.


Thanks,
Philipp

**Comment by SampsonCrowley** [comment]
Done

**Comment by SampsonCrowley** [comment]
node 6 timed out. i don't think that's my fault though.. node 4 passed and tests on my local pc (node v8.1.4) all passed

**Comment by SampsonCrowley** [comment]
is there a way to re run the test?

**Comment by SampsonCrowley** [comment]
Well that was weird, BUT we're ready to rock and roll

**Pull request merged**
